[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  # Reduce bundle size
  NODE_ENV = "production"
  # Use custom Tailwind config for Netlify
  TAILWIND_CONFIG_PATH = "./tailwind.netlify.config.js"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # The plugin doesn't accept any inputs

[functions]
  # Use ESBuild which creates smaller bundles
  node_bundler = "esbuild"
  # Don't include these packages in the function bundle
  included_files = ["!node_modules/@next/swc*/**/*", "!node_modules/next/dist/compiled/webpack/**/*"]
  external_node_modules = [
    "@netlify/plugin-nextjs", 
    "@netlify/next",
    "next", 
    "react", 
    "react-dom",
    "@supabase/supabase-js",
    "framer-motion",
    "zustand",
    "@tailwindcss/*",
    "autoprefixer",
    "postcss"
  ]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[edge_functions]]
  path = "/*"
  function = "static-assets"

[[redirects]]
  from = "/*"
  to = "/fallback.html"
  status = 500
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-simple/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-simple"
  status = 200
